package agent

import (
	"context"
	"strings"
	"testing"

	"travel-agent-go/internal/config"
	"travel-agent-go/internal/domain"
	"travel-agent-go/internal/services"
	"travel-agent-go/internal/tools"
	"travel-agent-go/internal/validators"
)

func TestMultiAgentTravelPlanningAgentRunsRoleChain(t *testing.T) {
	t.Parallel()

	rag := &fakeRetriever{}
	ragTool := tools.NewRAGTool(rag)
	plannerTool := tools.NewPlannerTool(services.NewRulePlanner())
	mapTool := tools.NewMapTool(config.Config{}, nil)
	weatherService := services.NewWeatherService(config.Config{}, nil)
	routeTool := tools.NewRouteTool(services.NewRoutePlanningService(config.Config{}, nil))
	assembler := services.NewItineraryAssembler()
	validatorSet := validators.NewDefaultSet()
	webResearchTool := tools.NewWebResearchTool(services.NewWebResearchService(config.Config{}))
	fallback := NewDefaultTravelPlanningAgent(
		ragTool,
		webResearchTool,
		plannerTool,
		mapTool,
		routeTool,
		weatherService,
		assembler,
		validatorSet,
	)
	agent := NewMultiAgentTravelPlanningAgent(
		ragTool,
		webResearchTool,
		plannerTool,
		mapTool,
		routeTool,
		weatherService,
		assembler,
		validatorSet,
		fallback,
	)

	itinerary, err := agent.Generate(context.Background(), domain.TripRequest{
		Destination:        "Dali",
		StartDate:          "2026-06-10",
		EndDate:            "2026-06-11",
		Travelers:          2,
		Budget:             3000,
		Preferences:        []string{"food", "old town"},
		Pace:               "relaxed",
		DietaryPreferences: []string{"no spicy"},
		HotelLevel:         "comfort",
		SpecialNotes:       "sunset",
	})
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}
	if !rag.called {
		t.Fatalf("expected research agent to call rag search")
	}
	if len(itinerary.Days) != 2 {
		t.Fatalf("expected 2 itinerary days, got %d", len(itinerary.Days))
	}
	if !strings.Contains(strings.Join(itinerary.SourceNotes, "\n"), "Generated by multi-agent orchestration.") {
		t.Fatalf("expected multi-agent source note, got %#v", itinerary.SourceNotes)
	}
	if itinerary.TripID == "" || itinerary.Summary == "" {
		t.Fatalf("expected finalized itinerary, got %#v", itinerary)
	}
}
