package agent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"travel-agent-go/internal/domain"
	"travel-agent-go/internal/logging"
	"travel-agent-go/internal/services"
	"travel-agent-go/internal/tools"
	"travel-agent-go/internal/validators"
)

// MultiAgentTravelPlanningAgent runs a role-based, sequential agent crew.
// It keeps orchestration deterministic while giving each sub-agent a narrow
// responsibility and a visible trace boundary.
type MultiAgentTravelPlanningAgent struct {
	agents   []RoleAgent
	fallback *TravelPlanningAgent
}

// RoleAgent is one worker in the multi-agent planning chain.
type RoleAgent interface {
	Name() string
	Role() string
	Goal() string
	Run(ctx context.Context, state *State) error
}

type roleAgent struct {
	name string
	role string
	goal string
	run  func(ctx context.Context, state *State) error
}

func newRoleAgent(name, role, goal string, run func(ctx context.Context, state *State) error) RoleAgent {
	return roleAgent{name: name, role: role, goal: goal, run: run}
}

func (a roleAgent) Name() string {
	return a.name
}

func (a roleAgent) Role() string {
	return a.role
}

func (a roleAgent) Goal() string {
	return a.goal
}

func (a roleAgent) Run(ctx context.Context, state *State) error {
	return a.run(ctx, state)
}

func NewMultiAgentTravelPlanningAgent(
	ragTool *tools.RAGTool,
	webResearchTool *tools.WebResearchTool,
	plannerTool *tools.PlannerTool,
	mapTool *tools.MapTool,
	routeTool *tools.RouteTool,
	weatherService *services.WeatherService,
	assembler *services.ItineraryAssembler,
	validatorSet *validators.Set,
	fallback *TravelPlanningAgent,
) *MultiAgentTravelPlanningAgent {
	return &MultiAgentTravelPlanningAgent{
		agents: []RoleAgent{
			newRoleAgent(
				"request_agent",
				"需求理解 Agent",
				"标准化旅行请求，计算行程天数，并保留用户约束。",
				runRequestAgent,
			),
			newRoleAgent(
				"research_agent",
				"资料研究 Agent",
				"收集在线证据、本地攻略和天气上下文，给规划阶段提供可靠材料。",
				runResearchAgent(ragTool, webResearchTool, weatherService),
			),
			newRoleAgent(
				"planning_agent",
				"行程规划 Agent",
				"基于请求和研究上下文生成结构化行程草稿并组装 itinerary。",
				runPlanningAgent(plannerTool, assembler),
			),
			newRoleAgent(
				"logistics_agent",
				"地图路线 Agent",
				"补充地图 POI 和真实路线信息，让行程更可执行。",
				runLogisticsAgent(mapTool, routeTool),
			),
			newRoleAgent(
				"review_agent",
				"质量审核 Agent",
				"检查预算、节奏、偏好、路线和占位内容，并执行规则级修复。",
				runReviewAgent(validatorSet),
			),
			newRoleAgent(
				"finalizer_agent",
				"最终整理 Agent",
				"清洗最终结果，挂载证据和来源说明。",
				runFinalizerAgent,
			),
		},
		fallback: fallback,
	}
}

func (a *MultiAgentTravelPlanningAgent) Generate(ctx context.Context, request domain.TripRequest) (domain.Itinerary, error) {
	start := time.Now()
	logging.Info(ctx, "multi-agent generation started",
		"destination", request.Destination,
		"start_date", request.StartDate,
		"end_date", request.EndDate,
		"travelers", request.Travelers,
		"budget", request.Budget,
		"preferences", len(request.Preferences),
		"dietary_preferences", len(request.DietaryPreferences),
		"pace", request.Pace,
		"hotel_level", request.HotelLevel,
		"special_notes_chars", len([]rune(request.SpecialNotes)),
		"agents", len(a.agents),
	)

	state := &State{Request: request}
	if err := a.run(ctx, state); err != nil {
		logging.Warn(ctx, "multi-agent generation failed, using fallback",
			"destination", request.Destination,
			"duration_ms", time.Since(start).Milliseconds(),
			"error", err,
		)
		return a.generateFallback(ctx, request)
	}
	if !hasUsableItinerary(state.FinalItinerary) {
		logging.Warn(ctx, "multi-agent produced no itinerary, using fallback",
			"destination", request.Destination,
			"duration_ms", time.Since(start).Milliseconds(),
		)
		return a.generateFallback(ctx, request)
	}

	state.FinalItinerary.SourceNotes = append(
		state.FinalItinerary.SourceNotes,
		"Generated by multi-agent orchestration.",
	)
	logging.Info(ctx, "multi-agent generation completed",
		"trip_id", state.FinalItinerary.TripID,
		"days", len(state.FinalItinerary.Days),
		"trace_steps", len(state.Trace),
		"duration_ms", time.Since(start).Milliseconds(),
	)
	return state.FinalItinerary, nil
}

func (a *MultiAgentTravelPlanningAgent) run(ctx context.Context, state *State) error {
	for _, worker := range a.agents {
		start := time.Now()
		state.AddTrace(worker.Name(), worker.Role()+" started: "+worker.Goal())
		startArgs := append([]any{
			"agent", worker.Name(),
			"role", worker.Role(),
			"goal", worker.Goal(),
		}, stepStateLogArgs(state)...)
		logging.Info(ctx, "multi-agent worker started", startArgs...)

		if err := worker.Run(ctx, state); err != nil {
			state.AddTrace(worker.Name(), "failed: "+err.Error())
			errorArgs := append([]any{
				"agent", worker.Name(),
				"role", worker.Role(),
				"duration_ms", time.Since(start).Milliseconds(),
				"error", err,
			}, stepStateLogArgs(state)...)
			logging.Error(ctx, "multi-agent worker failed", errorArgs...)
			return fmt.Errorf("%s: %w", worker.Name(), err)
		}

		state.AddTrace(worker.Name(), "completed")
		completedArgs := append([]any{
			"agent", worker.Name(),
			"role", worker.Role(),
			"duration_ms", time.Since(start).Milliseconds(),
		}, stepStateLogArgs(state)...)
		logging.Info(ctx, "multi-agent worker completed", completedArgs...)
	}
	return nil
}

func (a *MultiAgentTravelPlanningAgent) generateFallback(ctx context.Context, request domain.TripRequest) (domain.Itinerary, error) {
	if a.fallback == nil {
		return domain.Itinerary{}, errors.New("multi-agent fallback is not configured")
	}
	return a.fallback.Generate(ctx, request)
}

func runRequestAgent(ctx context.Context, state *State) error {
	return understandRequestStep(ctx, state)
}

func runResearchAgent(
	ragTool *tools.RAGTool,
	webResearchTool *tools.WebResearchTool,
	weatherService *services.WeatherService,
) func(ctx context.Context, state *State) error {
	return func(ctx context.Context, state *State) error {
		if webResearchTool != nil {
			if err := researchOnlineEvidenceStep(webResearchTool)(ctx, state); err != nil {
				return err
			}
		}
		if ragTool != nil {
			if err := retrieveContextStep(ragTool)(ctx, state); err != nil {
				return err
			}
		}
		if weatherService != nil {
			if err := loadWeatherStep(weatherService)(ctx, state); err != nil {
				return err
			}
		}
		return nil
	}
}

func runPlanningAgent(
	plannerTool *tools.PlannerTool,
	assembler *services.ItineraryAssembler,
) func(ctx context.Context, state *State) error {
	return func(ctx context.Context, state *State) error {
		if plannerTool == nil {
			return errors.New("planner tool is not configured")
		}
		if assembler == nil {
			return errors.New("itinerary assembler is not configured")
		}
		if err := generateDraftStep(plannerTool)(ctx, state); err != nil {
			return err
		}
		return assembleItineraryStep(assembler)(ctx, state)
	}
}

func runLogisticsAgent(
	mapTool *tools.MapTool,
	routeTool *tools.RouteTool,
) func(ctx context.Context, state *State) error {
	return func(ctx context.Context, state *State) error {
		if !hasUsableItinerary(state.FinalItinerary) {
			return errors.New("no itinerary to enrich")
		}
		if mapTool != nil {
			if err := enrichMapStep(mapTool)(ctx, state); err != nil {
				return err
			}
		}
		if routeTool != nil {
			if err := enrichRoutesStep(routeTool)(ctx, state); err != nil {
				return err
			}
		}
		return nil
	}
}

func runReviewAgent(validatorSet *validators.Set) func(ctx context.Context, state *State) error {
	return func(ctx context.Context, state *State) error {
		if !hasUsableItinerary(state.FinalItinerary) {
			return errors.New("no itinerary to review")
		}
		if validatorSet == nil {
			state.AddTrace("review_agent", "validator set is not configured")
			return nil
		}
		if err := validateItineraryStep(validatorSet)(ctx, state); err != nil {
			return err
		}
		if len(state.ValidationIssues) == 0 {
			return nil
		}

		before := len(state.ValidationIssues)
		if err := repairItineraryStep(ctx, state); err != nil {
			return err
		}
		if err := validateItineraryStep(validatorSet)(ctx, state); err != nil {
			return err
		}
		state.AddTrace("review_agent", "复核完成，问题数量："+itoa(before)+" -> "+itoa(len(state.ValidationIssues)))
		return nil
	}
}

func runFinalizerAgent(ctx context.Context, state *State) error {
	if !hasUsableItinerary(state.FinalItinerary) {
		return errors.New("no itinerary to finalize")
	}
	return finalizeStep(ctx, state)
}
