package agent

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"zhilv-yuntu-go/internal/config"
	"zhilv-yuntu-go/internal/domain"
	"zhilv-yuntu-go/internal/services"
	"zhilv-yuntu-go/internal/tools"
	"zhilv-yuntu-go/internal/validators"
)

func TestToolCallingTravelPlanningAgentRunsModelSelectedTools(t *testing.T) {
	t.Parallel()

	var chatCalls int
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path != "/chat/completions" {
			t.Fatalf("unexpected path: %s", r.URL.Path)
		}

		var request toolChatRequest
		if err := json.NewDecoder(r.Body).Decode(&request); err != nil {
			t.Fatalf("decode request: %v", err)
		}
		if len(request.Tools) == 0 {
			t.Fatalf("expected tool definitions in request")
		}

		chatCalls++
		writeToolChatResponse(t, w, toolChatResponseForTurn(chatCalls))
	}))
	defer server.Close()

	rag := &fakeRetriever{}
	planner := services.NewRulePlanner()
	ragTool := tools.NewRAGTool(rag)
	plannerTool := tools.NewPlannerTool(planner)
	mapTool := tools.NewMapTool(config.Config{})
	assembler := services.NewItineraryAssembler()
	validatorSet := validators.NewDefaultSet()
	fallback := NewDefaultTravelPlanningAgent(ragTool, plannerTool, mapTool, assembler, validatorSet)
	agent := NewToolCallingTravelPlanningAgent(
		config.Config{
			LLMAPIKey:         "test-key",
			LLMBaseURL:        server.URL,
			LLMModel:          "test-model",
			LLMTimeoutSeconds: 5,
		},
		ragTool,
		tools.NewWebResearchTool(services.NewWebResearchService(config.Config{})),
		plannerTool,
		mapTool,
		services.NewWeatherService(),
		assembler,
		validatorSet,
		fallback,
	)

	itinerary, err := agent.Generate(context.Background(), domain.TripRequest{
		Destination:        "Dali",
		StartDate:          "2026-06-10",
		EndDate:            "2026-06-11",
		Travelers:          2,
		Budget:             3000,
		Preferences:        []string{"food", "old town"},
		Pace:               "relaxed",
		DietaryPreferences: []string{"no spicy"},
		HotelLevel:         "comfort",
		SpecialNotes:       "sunset",
	})
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}
	if !rag.called {
		t.Fatalf("expected rag_search tool to be executed")
	}
	if chatCalls != 5 {
		t.Fatalf("expected 5 tool-calling chat turns, got %d", chatCalls)
	}
	if len(itinerary.Days) != 2 {
		t.Fatalf("expected 2 itinerary days, got %d", len(itinerary.Days))
	}
	if !strings.Contains(strings.Join(itinerary.SourceNotes, "\n"), "Generated by LLM tool-calling agent.") {
		t.Fatalf("expected tool-calling source note, got %#v", itinerary.SourceNotes)
	}

	state := &State{Request: domain.TripRequest{Destination: "Dali"}}
	result := agent.callWeatherForecast(context.Background(), state, `{"city":"Dali"}`)
	observation := NewToolObservation(toolCall{
		ID: "call_weather",
		Function: toolCallFunction{
			Name:      string(ToolWeatherForecast),
			Arguments: `{"city":"Dali"}`,
		},
	}, result)
	if observation.Name != ToolWeatherForecast || !observation.OK {
		t.Fatalf("unexpected observation: %#v", observation)
	}
	if len(observation.Result) == 0 || !strings.Contains(string(observation.Result), `"forecast"`) {
		t.Fatalf("expected structured weather result, got %s", observation.Result)
	}
}

func TestToolCallingTravelPlanningAgentRunsWebResearchTool(t *testing.T) {
	t.Parallel()

	searchServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/search":
			_ = json.NewEncoder(w).Encode(map[string]any{
				"results": []map[string]string{
					{"url": "http://" + r.Host + "/guide"},
				},
			})
		case "/guide":
			w.Header().Set("Content-Type", "text/html; charset=utf-8")
			_, _ = w.Write([]byte(`<html><head><title>Dali online guide</title></head><body><p>Online guide says Xizhou old town is good for snacks and sunset routes.</p></body></html>`))
		default:
			http.NotFound(w, r)
		}
	}))
	defer searchServer.Close()

	ragTool := tools.NewRAGTool(&fakeRetriever{})
	plannerTool := tools.NewPlannerTool(services.NewRulePlanner())
	mapTool := tools.NewMapTool(config.Config{})
	assembler := services.NewItineraryAssembler()
	validatorSet := validators.NewDefaultSet()
	fallback := NewDefaultTravelPlanningAgent(ragTool, plannerTool, mapTool, assembler, validatorSet)
	agent := NewToolCallingTravelPlanningAgent(
		config.Config{
			LLMAPIKey:           "test-key",
			LLMBaseURL:          "http://unused",
			LLMModel:            "test-model",
			LLMTimeoutSeconds:   5,
			EnableWebResearch:   true,
			WebSearchEndpoint:   searchServer.URL + "/search",
			WebResearchTimeout:  5,
			WebResearchMaxPages: 1,
		},
		ragTool,
		tools.NewWebResearchTool(services.NewWebResearchService(config.Config{
			EnableWebResearch:   true,
			WebSearchEndpoint:   searchServer.URL + "/search",
			WebResearchTimeout:  5,
			WebResearchMaxPages: 1,
		})),
		plannerTool,
		mapTool,
		services.NewWeatherService(),
		assembler,
		validatorSet,
		fallback,
	)

	state := &State{Request: domain.TripRequest{Destination: "Dali"}}
	result := agent.callWebResearch(context.Background(), state, `{"destination":"Dali","top_k":1}`)
	if !result.OK {
		t.Fatalf("web research failed: %#v", result)
	}
	if len(state.RAGContexts) != 1 {
		t.Fatalf("expected one online context, got %d", len(state.RAGContexts))
	}
	if !strings.Contains(state.RAGContexts[0], "Online guide") {
		t.Fatalf("expected online guide context, got %q", state.RAGContexts[0])
	}
}

func toolChatResponseForTurn(turn int) toolChatResponse {
	switch turn {
	case 1:
		return responseWithToolCall("call_rag", "rag_search", `{"destination":"Dali","top_k":2}`)
	case 2:
		return responseWithToolCall("call_weather", "weather_forecast", `{"city":"Dali"}`)
	case 3:
		return responseWithToolCall("call_plan", "generate_itinerary_draft", `{"day_count":2}`)
	case 4:
		return responseWithToolCall("call_validate", "validate_itinerary", `{}`)
	default:
		return responseWithToolCall("call_finish", "finish_itinerary", `{}`)
	}
}

func responseWithToolCall(id, name, arguments string) toolChatResponse {
	return toolChatResponse{
		Choices: []toolChatChoice{
			{
				Message: toolChatMessage{
					Role: "assistant",
					ToolCalls: []toolCall{
						{
							ID:   id,
							Type: "function",
							Function: toolCallFunction{
								Name:      name,
								Arguments: arguments,
							},
						},
					},
				},
			},
		},
	}
}

func writeToolChatResponse(t *testing.T, w http.ResponseWriter, response toolChatResponse) {
	t.Helper()
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(response); err != nil {
		t.Fatalf("encode response: %v", err)
	}
}

type fakeRetriever struct {
	called bool
}

func (r *fakeRetriever) Retrieve(destination string, preferences []string, pace string, specialNotes string, topK int) ([]string, error) {
	r.called = true
	return []string{
		"[source: test]\nDali has old towns, lake scenery, and sunset routes.",
	}, nil
}
