package agent

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"

	"zhilv-yuntu-go/internal/config"
	"zhilv-yuntu-go/internal/domain"
	"zhilv-yuntu-go/internal/logging"
	"zhilv-yuntu-go/internal/services"
	"zhilv-yuntu-go/internal/tools"
	"zhilv-yuntu-go/internal/validators"
)

const defaultToolCallingMaxTurns = 8

// ToolCallingTravelPlanningAgent lets an OpenAI-compatible model decide which
// tools to call, while Go still owns the actual tool execution and validation.
type ToolCallingTravelPlanningAgent struct {
	cfg             config.Config
	client          *http.Client
	ragTool         *tools.RAGTool
	webResearchTool *tools.WebResearchTool
	plannerTool     *tools.PlannerTool
	mapTool         *tools.MapTool
	weatherService  *services.WeatherService
	assembler       *services.ItineraryAssembler
	validatorSet    *validators.Set
	fallback        *TravelPlanningAgent
	maxTurns        int
}

func NewToolCallingTravelPlanningAgent(
	cfg config.Config,
	ragTool *tools.RAGTool,
	webResearchTool *tools.WebResearchTool,
	plannerTool *tools.PlannerTool,
	mapTool *tools.MapTool,
	weatherService *services.WeatherService,
	assembler *services.ItineraryAssembler,
	validatorSet *validators.Set,
	fallback *TravelPlanningAgent,
) *ToolCallingTravelPlanningAgent {
	return &ToolCallingTravelPlanningAgent{
		cfg:             cfg,
		client:          &http.Client{Timeout: time.Duration(cfg.LLMTimeoutSeconds) * time.Second},
		ragTool:         ragTool,
		webResearchTool: webResearchTool,
		plannerTool:     plannerTool,
		mapTool:         mapTool,
		weatherService:  weatherService,
		assembler:       assembler,
		validatorSet:    validatorSet,
		fallback:        fallback,
		maxTurns:        defaultToolCallingMaxTurns,
	}
}

func (a *ToolCallingTravelPlanningAgent) Generate(ctx context.Context, request domain.TripRequest) (domain.Itinerary, error) {
	start := time.Now()
	if strings.TrimSpace(a.cfg.LLMAPIKey) == "" {
		logging.Info(ctx, "tool-calling agent disabled, using fallback",
			"destination", request.Destination,
		)
		return a.fallback.Generate(ctx, request)
	}

	logging.Info(ctx, "tool-calling agent generation started",
		"destination", request.Destination,
		"start_date", request.StartDate,
		"end_date", request.EndDate,
		"model", a.cfg.LLMModel,
	)

	state := &State{
		Request:  request,
		DayCount: calcDayCount(request.StartDate, request.EndDate),
	}
	state.AddTrace("tool_agent", "starting tool-calling loop")

	if err := a.runToolLoop(ctx, state); err != nil {
		state.AddTrace("tool_agent", "tool-calling failed, falling back: "+err.Error())
		logging.Warn(ctx, "tool-calling agent failed, using fallback",
			"destination", request.Destination,
			"duration_ms", time.Since(start).Milliseconds(),
			"error", err,
		)
		return a.fallback.Generate(ctx, request)
	}
	if !hasUsableItinerary(state.FinalItinerary) {
		state.AddTrace("tool_agent", "tool-calling finished without itinerary, falling back")
		logging.Warn(ctx, "tool-calling agent produced no itinerary, using fallback",
			"destination", request.Destination,
			"duration_ms", time.Since(start).Milliseconds(),
		)
		return a.fallback.Generate(ctx, request)
	}

	if len(state.ValidationIssues) > 0 {
		logging.Info(ctx, "tool-calling agent repairing validation issues",
			"issues", len(state.ValidationIssues),
		)
		if err := repairItineraryStep(ctx, state); err != nil {
			logging.Error(ctx, "tool-calling agent repair failed",
				"duration_ms", time.Since(start).Milliseconds(),
				"error", err,
			)
			return domain.Itinerary{}, err
		}
	}
	if err := finalizeStep(ctx, state); err != nil {
		logging.Error(ctx, "tool-calling agent finalize failed",
			"duration_ms", time.Since(start).Milliseconds(),
			"error", err,
		)
		return domain.Itinerary{}, err
	}
	state.FinalItinerary.SourceNotes = append(
		state.FinalItinerary.SourceNotes,
		"Generated by LLM tool-calling agent.",
	)
	logging.Info(ctx, "tool-calling agent generation completed",
		"trip_id", state.FinalItinerary.TripID,
		"days", len(state.FinalItinerary.Days),
		"trace_steps", len(state.Trace),
		"tool_observations", len(state.ToolObservations),
		"duration_ms", time.Since(start).Milliseconds(),
	)
	return state.FinalItinerary, nil
}

func (a *ToolCallingTravelPlanningAgent) runToolLoop(ctx context.Context, state *State) error {
	messages := []toolChatMessage{
		{Role: "system", Content: a.systemPrompt()},
		{Role: "user", Content: buildTripRequestPrompt(state.Request, state.DayCount)},
	}

	for turn := 0; turn < a.maxTurns; turn++ {
		turnStart := time.Now()
		logging.Info(ctx, "tool-calling turn started",
			"turn", turn+1,
			"messages", len(messages),
		)
		assistantMessage, err := a.chat(ctx, messages)
		if err != nil {
			logging.Error(ctx, "tool-calling turn failed",
				"turn", turn+1,
				"duration_ms", time.Since(turnStart).Milliseconds(),
				"error", err,
			)
			return err
		}
		if len(assistantMessage.ToolCalls) == 0 {
			if hasUsableItinerary(state.FinalItinerary) {
				state.AddTrace("tool_agent", "model stopped after itinerary generation")
				logging.Info(ctx, "tool-calling loop stopped without further tool calls",
					"turn", turn+1,
					"duration_ms", time.Since(turnStart).Milliseconds(),
				)
				return nil
			}
			logging.Warn(ctx, "tool-calling model returned no tool calls",
				"turn", turn+1,
				"duration_ms", time.Since(turnStart).Milliseconds(),
			)
			return errors.New("model returned no tool calls")
		}
		logging.Info(ctx, "tool-calling model selected tools",
			"turn", turn+1,
			"tool_calls", len(assistantMessage.ToolCalls),
		)

		for i := range assistantMessage.ToolCalls {
			if assistantMessage.ToolCalls[i].ID == "" {
				assistantMessage.ToolCalls[i].ID = fmt.Sprintf("call_%d_%d", turn+1, i+1)
			}
			if assistantMessage.ToolCalls[i].Type == "" {
				assistantMessage.ToolCalls[i].Type = "function"
			}
		}
		messages = append(messages, assistantMessage)

		finished := false
		for _, call := range assistantMessage.ToolCalls {
			content, done := a.executeToolCall(ctx, state, call)
			messages = append(messages, toolChatMessage{
				Role:       "tool",
				ToolCallID: call.ID,
				Content:    content,
			})
			if done {
				finished = true
			}
		}
		if finished && hasUsableItinerary(state.FinalItinerary) {
			logging.Info(ctx, "tool-calling loop finished",
				"turn", turn+1,
				"duration_ms", time.Since(turnStart).Milliseconds(),
			)
			return nil
		}
		logging.Info(ctx, "tool-calling turn completed",
			"turn", turn+1,
			"duration_ms", time.Since(turnStart).Milliseconds(),
		)
	}

	if hasUsableItinerary(state.FinalItinerary) {
		return nil
	}
	return errors.New("tool-calling loop reached max turns without an itinerary")
}

func (a *ToolCallingTravelPlanningAgent) chat(ctx context.Context, messages []toolChatMessage) (toolChatMessage, error) {
	start := time.Now()
	baseURL := strings.TrimRight(a.cfg.LLMBaseURL, "/")
	if baseURL == "" {
		baseURL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
	}

	body := toolChatRequest{
		Model:       a.cfg.LLMModel,
		Messages:    messages,
		Tools:       toolDefinitions(),
		ToolChoice:  "auto",
		Temperature: 0.2,
	}
	data, err := json.Marshal(body)
	if err != nil {
		return toolChatMessage{}, err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, baseURL+"/chat/completions", bytes.NewReader(data))
	if err != nil {
		return toolChatMessage{}, err
	}
	req.Header.Set("Authorization", "Bearer "+a.cfg.LLMAPIKey)
	req.Header.Set("Content-Type", "application/json")

	logging.Info(ctx, "tool-calling chat request started",
		"model", a.cfg.LLMModel,
		"messages", len(messages),
		"url", baseURL+"/chat/completions",
	)
	resp, err := a.client.Do(req)
	if err != nil {
		logging.Error(ctx, "tool-calling chat request failed",
			"model", a.cfg.LLMModel,
			"duration_ms", time.Since(start).Milliseconds(),
			"error", err,
		)
		return toolChatMessage{}, err
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return toolChatMessage{}, err
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		logging.Error(ctx, "tool-calling chat response failed",
			"model", a.cfg.LLMModel,
			"status", resp.StatusCode,
			"duration_ms", time.Since(start).Milliseconds(),
			"error", trimBody(respBody),
		)
		return toolChatMessage{}, errors.New(trimBody(respBody))
	}

	var parsed toolChatResponse
	if err := json.Unmarshal(respBody, &parsed); err != nil {
		return toolChatMessage{}, err
	}
	if len(parsed.Choices) == 0 {
		return toolChatMessage{}, errors.New("tool-calling response has no choices")
	}
	logging.Info(ctx, "tool-calling chat request completed",
		"model", a.cfg.LLMModel,
		"status", resp.StatusCode,
		"duration_ms", time.Since(start).Milliseconds(),
		"choices", len(parsed.Choices),
	)
	return parsed.Choices[0].Message, nil
}

func (a *ToolCallingTravelPlanningAgent) executeToolCall(ctx context.Context, state *State, call toolCall) (string, bool) {
	name := ToolName(call.Function.Name)
	start := time.Now()
	logging.Info(ctx, "tool call started",
		"tool", string(name),
		"tool_call_id", call.ID,
	)
	state.AddTrace("tool_call", "calling "+string(name))

	result, done := a.runTool(ctx, state, call)
	state.AddToolObservation(NewToolObservation(call, result))
	if result.OK {
		logging.Info(ctx, "tool call completed",
			"tool", string(name),
			"tool_call_id", call.ID,
			"done", done,
			"duration_ms", time.Since(start).Milliseconds(),
		)
	} else {
		logging.Warn(ctx, "tool call failed",
			"tool", string(name),
			"tool_call_id", call.ID,
			"done", done,
			"duration_ms", time.Since(start).Milliseconds(),
			"error", result.Error,
		)
	}
	return result.JSON(), done
}

func (a *ToolCallingTravelPlanningAgent) runTool(ctx context.Context, state *State, call toolCall) (ToolExecutionResult, bool) {
	name := ToolName(call.Function.Name)
	switch name {
	case ToolRAGSearch:
		return a.callRAGSearch(ctx, state, call.Function.Arguments), false
	case ToolWebResearch:
		return a.callWebResearch(ctx, state, call.Function.Arguments), false
	case ToolWeatherForecast:
		return a.callWeatherForecast(ctx, state, call.Function.Arguments), false
	case ToolGenerateItineraryDraft:
		return a.callGenerateItineraryDraft(ctx, state, call.Function.Arguments), false
	case ToolEnrichMap:
		return a.callEnrichMap(ctx, state), false
	case ToolValidateItinerary:
		return a.callValidateItinerary(ctx, state), false
	case ToolRepairItinerary:
		return a.callRepairItinerary(ctx, state), false
	case ToolFinishItinerary:
		if !hasUsableItinerary(state.FinalItinerary) {
			return NewToolError(name, errors.New("cannot finish before generate_itinerary_draft creates an itinerary")), false
		}
		return NewToolOK(name, FinishItineraryToolResult{
			TripID:          state.FinalItinerary.TripID,
			Days:            len(state.FinalItinerary.Days),
			EstimatedBudget: state.FinalItinerary.EstimatedBudget,
		}), true
	default:
		return NewToolError(name, fmt.Errorf("unknown tool %q", name)), false
	}
}

func (a *ToolCallingTravelPlanningAgent) callWebResearch(ctx context.Context, state *State, rawArgs string) ToolExecutionResult {
	var args WebResearchToolArgs
	if err := decodeToolArgs(rawArgs, &args); err != nil {
		return NewToolError(ToolWebResearch, err)
	}
	args.Normalize(state.Request)
	logging.Info(ctx, "web research tool requested",
		"destination", args.Destination,
		"query", args.Query,
		"top_k", args.TopK,
	)
	if a.webResearchTool == nil {
		logging.Warn(ctx, "web research tool unavailable",
			"destination", args.Destination,
			"query", args.Query,
		)
		return NewToolOK(ToolWebResearch, WebResearchToolResult{
			Query:    args.Query,
			Disabled: true,
		})
	}

	result, err := a.webResearchTool.Research(ctx, tools.WebResearchInput{
		Destination: args.Destination,
		Query:       args.Query,
		TopK:        args.TopK,
	})
	if err != nil {
		logging.Warn(ctx, "web research tool failed",
			"destination", args.Destination,
			"query", args.Query,
			"error", err,
		)
		return NewToolError(ToolWebResearch, err)
	}

	digests := make([]WebResearchSourceDigest, 0, len(result.Sources))
	contexts := make([]string, 0, len(result.Sources))
	for _, source := range result.Sources {
		digest := WebResearchSourceDigest{
			Title:   source.Title,
			URL:     source.URL,
			Snippet: source.Snippet,
		}
		digests = append(digests, digest)
		contexts = append(contexts, formatWebResearchContext(digest))
	}
	state.RAGContexts = appendUniqueStrings(state.RAGContexts, contexts...)
	state.AddTrace(string(ToolWebResearch), fmt.Sprintf("found %d online sources", len(digests)))
	logging.Info(ctx, "web research tool completed",
		"query", result.Query,
		"sources", len(digests),
		"contexts", len(contexts),
	)
	return NewToolOK(ToolWebResearch, WebResearchToolResult{
		Query:   result.Query,
		Count:   len(digests),
		Sources: digests,
	})
}

func (a *ToolCallingTravelPlanningAgent) callRAGSearch(ctx context.Context, state *State, rawArgs string) ToolExecutionResult {
	var args RAGSearchToolArgs
	if err := decodeToolArgs(rawArgs, &args); err != nil {
		return NewToolError(ToolRAGSearch, err)
	}
	args.Normalize(state.Request)
	logging.Info(ctx, "rag search tool requested",
		"destination", args.Destination,
		"preferences", len(args.Preferences),
		"pace", args.Pace,
		"top_k", args.TopK,
	)

	contexts, err := a.ragTool.Search(ctx, tools.RAGSearchInput{
		Destination:  args.Destination,
		Preferences:  args.Preferences,
		Pace:         args.Pace,
		SpecialNotes: args.SpecialNotes,
		TopK:         args.TopK,
	})
	if err != nil {
		logging.Warn(ctx, "rag search tool failed",
			"destination", args.Destination,
			"error", err,
		)
		return NewToolError(ToolRAGSearch, err)
	}
	state.RAGContexts = appendUniqueStrings(state.RAGContexts, contexts...)
	state.AddTrace(string(ToolRAGSearch), fmt.Sprintf("found %d context chunks", len(contexts)))
	logging.Info(ctx, "rag search tool completed",
		"destination", args.Destination,
		"contexts", len(contexts),
	)
	return NewToolOK(ToolRAGSearch, RAGSearchToolResult{
		Count:    len(contexts),
		Contexts: contexts,
	})
}

func (a *ToolCallingTravelPlanningAgent) callWeatherForecast(ctx context.Context, state *State, rawArgs string) ToolExecutionResult {
	var args WeatherForecastToolArgs
	if err := decodeToolArgs(rawArgs, &args); err != nil {
		return NewToolError(ToolWeatherForecast, err)
	}
	args.Normalize(state.Request)
	logging.Info(ctx, "weather forecast tool requested", "city", args.City)
	if a.weatherService == nil {
		return NewToolError(ToolWeatherForecast, errors.New("weather service is not configured"))
	}

	forecast := a.weatherService.Forecast(ctx, args.City)
	contextText := formatWeatherContext(forecast)
	if contextText != "" {
		state.RAGContexts = appendUniqueStrings(state.RAGContexts, contextText)
	}
	state.AddTrace(string(ToolWeatherForecast), "loaded weather for "+args.City)
	logging.Info(ctx, "weather forecast tool completed",
		"city", args.City,
		"days", len(forecast.Days),
		"context_added", contextText != "",
	)
	return NewToolOK(ToolWeatherForecast, WeatherForecastToolResult{
		Forecast:     forecast,
		ContextAdded: contextText != "",
	})
}

func (a *ToolCallingTravelPlanningAgent) callGenerateItineraryDraft(ctx context.Context, state *State, rawArgs string) ToolExecutionResult {
	var args GenerateItineraryDraftToolArgs
	if err := decodeToolArgs(rawArgs, &args); err != nil {
		return NewToolError(ToolGenerateItineraryDraft, err)
	}
	dayCount := args.EffectiveDayCount(state.DayCount)
	if dayCount <= 0 {
		dayCount = calcDayCount(state.Request.StartDate, state.Request.EndDate)
	}
	state.DayCount = dayCount
	logging.Info(ctx, "planner draft tool requested",
		"destination", state.Request.Destination,
		"day_count", dayCount,
		"contexts", len(state.RAGContexts),
	)

	draft, err := a.plannerTool.Generate(ctx, tools.PlannerInput{
		Request:  state.Request,
		Contexts: state.RAGContexts,
		DayCount: dayCount,
	})
	if err != nil {
		logging.Warn(ctx, "planner draft tool failed",
			"destination", state.Request.Destination,
			"day_count", dayCount,
			"error", err,
		)
		return NewToolError(ToolGenerateItineraryDraft, err)
	}

	state.PlannerDraft = draft
	itinerary := a.assembler.Assemble(state.Request, draft, state.RAGContexts, dayCount)
	state.DraftItinerary = itinerary
	state.FinalItinerary = itinerary
	state.AddTrace(string(ToolGenerateItineraryDraft), fmt.Sprintf("generated %d days", len(itinerary.Days)))
	logging.Info(ctx, "planner draft tool completed",
		"trip_id", itinerary.TripID,
		"days", len(itinerary.Days),
		"estimated_budget", itinerary.EstimatedBudget,
	)
	return NewToolOK(ToolGenerateItineraryDraft, GenerateItineraryDraftToolResult{
		TripID:          itinerary.TripID,
		Summary:         itinerary.Summary,
		Days:            len(itinerary.Days),
		EstimatedBudget: itinerary.EstimatedBudget,
	})
}

func (a *ToolCallingTravelPlanningAgent) callEnrichMap(ctx context.Context, state *State) ToolExecutionResult {
	if !hasUsableItinerary(state.FinalItinerary) {
		return NewToolError(ToolEnrichMap, errors.New("no itinerary to enrich"))
	}
	if a.mapTool == nil {
		return NewToolError(ToolEnrichMap, errors.New("map tool is not configured"))
	}
	logging.Info(ctx, "map enrich tool requested",
		"trip_id", state.FinalItinerary.TripID,
		"days", len(state.FinalItinerary.Days),
	)
	if err := a.mapTool.EnrichItinerary(ctx, &state.FinalItinerary); err != nil {
		logging.Warn(ctx, "map enrich tool failed",
			"trip_id", state.FinalItinerary.TripID,
			"error", err,
		)
		return NewToolError(ToolEnrichMap, err)
	}
	state.AddTrace(string(ToolEnrichMap), "map enrichment completed")
	logging.Info(ctx, "map enrich tool completed",
		"trip_id", state.FinalItinerary.TripID,
		"days", len(state.FinalItinerary.Days),
	)
	return NewToolOK(ToolEnrichMap, EnrichMapToolResult{Days: len(state.FinalItinerary.Days)})
}

func (a *ToolCallingTravelPlanningAgent) callValidateItinerary(ctx context.Context, state *State) ToolExecutionResult {
	if !hasUsableItinerary(state.FinalItinerary) {
		return NewToolError(ToolValidateItinerary, errors.New("no itinerary to validate"))
	}
	issues := a.validatorSet.Validate(state.Request, state.FinalItinerary)
	state.ValidationIssues = make([]ValidationIssue, 0, len(issues))
	for _, issue := range issues {
		state.ValidationIssues = append(state.ValidationIssues, ValidationIssue{
			Code:     issue.Code,
			Level:    issue.Level,
			Message:  issue.Message,
			DayIndex: issue.DayIndex,
		})
	}
	state.AddTrace(string(ToolValidateItinerary), fmt.Sprintf("found %d issues", len(issues)))
	logging.Info(ctx, "itinerary validation tool completed",
		"trip_id", state.FinalItinerary.TripID,
		"issues", len(issues),
	)
	return NewToolOK(ToolValidateItinerary, ValidateItineraryToolResult{
		Count:  len(state.ValidationIssues),
		Issues: state.ValidationIssues,
	})
}

func (a *ToolCallingTravelPlanningAgent) callRepairItinerary(ctx context.Context, state *State) ToolExecutionResult {
	if !hasUsableItinerary(state.FinalItinerary) {
		return NewToolError(ToolRepairItinerary, errors.New("no itinerary to repair"))
	}
	if len(state.ValidationIssues) == 0 {
		_ = a.callValidateItinerary(ctx, state)
	}
	logging.Info(ctx, "itinerary repair tool requested",
		"trip_id", state.FinalItinerary.TripID,
		"known_issues", len(state.ValidationIssues),
	)
	if err := repairItineraryStep(ctx, state); err != nil {
		logging.Warn(ctx, "itinerary repair tool failed",
			"trip_id", state.FinalItinerary.TripID,
			"error", err,
		)
		return NewToolError(ToolRepairItinerary, err)
	}
	state.AddTrace(string(ToolRepairItinerary), "repair completed")
	logging.Info(ctx, "itinerary repair tool completed",
		"trip_id", state.FinalItinerary.TripID,
		"remaining_known_issues", len(state.ValidationIssues),
	)
	return NewToolOK(ToolRepairItinerary, RepairItineraryToolResult{
		RemainingKnownIssues: len(state.ValidationIssues),
	})
}

func (a *ToolCallingTravelPlanningAgent) systemPrompt() string {
	return strings.Join([]string{
		"You are a travel-planning agent. You must decide which tools are needed and call them.",
		"Use rag_search when local travel guide context would improve the plan.",
		"Use web_research when current online travel guides, blog posts, or public攻略 pages would improve attraction, food, route, or caution details.",
		"Use weather_forecast when weather may affect itinerary tips, clothes, transport, or pacing.",
		"Call generate_itinerary_draft to create the itinerary after gathering useful context.",
		"Call enrich_map only after an itinerary exists and map/POI enrichment is useful.",
		"Call validate_itinerary after generating or changing an itinerary.",
		"Call repair_itinerary when validation reports issues.",
		"Call finish_itinerary only when the itinerary is ready for the user.",
		"Do not answer with prose instead of tools while the itinerary is unfinished.",
	}, "\n")
}

func buildTripRequestPrompt(request domain.TripRequest, dayCount int) string {
	data, err := json.MarshalIndent(request, "", "  ")
	if err != nil {
		data = []byte("{}")
	}
	return fmt.Sprintf(
		"Create a travel itinerary for this request. Computed day_count=%d.\nRequest JSON:\n%s",
		dayCount,
		string(data),
	)
}

func toolDefinitions() []toolDefinition {
	return []toolDefinition{
		{
			Type: "function",
			Function: toolFunctionDefinition{
				Name:        string(ToolRAGSearch),
				Description: "Search local markdown travel-guide knowledge for destination context, attractions, food, pacing, and notes.",
				Parameters: rawSchema(`{
					"type": "object",
					"properties": {
						"destination": {"type": "string"},
						"preferences": {"type": "array", "items": {"type": "string"}},
						"pace": {"type": "string"},
						"special_notes": {"type": "string"},
						"top_k": {"type": "integer", "minimum": 1, "maximum": 8}
					},
					"additionalProperties": false
				}`),
			},
		},
		{
			Type: "function",
			Function: toolFunctionDefinition{
				Name:        string(ToolWebResearch),
				Description: "Search online travel guide pages, fetch candidate pages, and extract useful snippets for itinerary planning.",
				Parameters: rawSchema(`{
					"type": "object",
					"properties": {
						"destination": {"type": "string"},
						"query": {"type": "string", "description": "Search query, for example: 大理 旅游攻略 美食 古镇 三日游"},
						"top_k": {"type": "integer", "minimum": 1, "maximum": 5}
					},
					"additionalProperties": false
				}`),
			},
		},
		{
			Type: "function",
			Function: toolFunctionDefinition{
				Name:        string(ToolWeatherForecast),
				Description: "Get a weather forecast for the destination city and add it as planning context.",
				Parameters: rawSchema(`{
					"type": "object",
					"properties": {
						"city": {"type": "string"}
					},
					"additionalProperties": false
				}`),
			},
		},
		{
			Type: "function",
			Function: toolFunctionDefinition{
				Name:        string(ToolGenerateItineraryDraft),
				Description: "Generate and assemble a structured itinerary using the current request and gathered context.",
				Parameters: rawSchema(`{
					"type": "object",
					"properties": {
						"day_count": {"type": "integer", "minimum": 1}
					},
					"additionalProperties": false
				}`),
			},
		},
		{
			Type: "function",
			Function: toolFunctionDefinition{
				Name:        string(ToolEnrichMap),
				Description: "Enrich generated spots with map POI data such as address, coordinates, image URL, and POI ID.",
				Parameters:  emptyObjectSchema(),
			},
		},
		{
			Type: "function",
			Function: toolFunctionDefinition{
				Name:        string(ToolValidateItinerary),
				Description: "Validate itinerary quality against budget, pacing, and preference constraints.",
				Parameters:  emptyObjectSchema(),
			},
		},
		{
			Type: "function",
			Function: toolFunctionDefinition{
				Name:        string(ToolRepairItinerary),
				Description: "Apply rule-based repairs for known validation issues.",
				Parameters:  emptyObjectSchema(),
			},
		},
		{
			Type: "function",
			Function: toolFunctionDefinition{
				Name:        string(ToolFinishItinerary),
				Description: "Finish the agent loop after a usable itinerary has been generated and validated.",
				Parameters:  emptyObjectSchema(),
			},
		},
	}
}

func rawSchema(value string) json.RawMessage {
	return json.RawMessage([]byte(value))
}

func emptyObjectSchema() json.RawMessage {
	return rawSchema(`{"type":"object","properties":{},"additionalProperties":false}`)
}

func decodeToolArgs(rawArgs string, target any) error {
	rawArgs = strings.TrimSpace(rawArgs)
	if rawArgs == "" {
		return nil
	}
	return json.NewDecoder(strings.NewReader(rawArgs)).Decode(target)
}

func appendUniqueStrings(values []string, additions ...string) []string {
	seen := make(map[string]bool, len(values)+len(additions))
	result := make([]string, 0, len(values)+len(additions))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		result = append(result, value)
	}
	for _, value := range additions {
		value = strings.TrimSpace(value)
		if value == "" || seen[value] {
			continue
		}
		seen[value] = true
		result = append(result, value)
	}
	return result
}

func formatWeatherContext(forecast domain.WeatherForecastResponse) string {
	if forecast.City == "" || len(forecast.Days) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("Weather forecast for ")
	b.WriteString(forecast.City)
	b.WriteString(":\n")
	for _, day := range forecast.Days {
		label := day.Date
		if label == "" {
			label = "week " + day.Week
		}
		b.WriteString("- ")
		b.WriteString(label)
		b.WriteString(": day=")
		b.WriteString(day.DayWeather)
		b.WriteString(", night=")
		b.WriteString(day.NightWeather)
		b.WriteString(", temp=")
		b.WriteString(day.NightTemp)
		b.WriteString("-")
		b.WriteString(day.DayTemp)
		b.WriteString("\n")
	}
	return b.String()
}

func formatWebResearchContext(source WebResearchSourceDigest) string {
	var b strings.Builder
	b.WriteString("[Online travel source")
	if source.Title != "" {
		b.WriteString(": ")
		b.WriteString(source.Title)
	}
	if source.URL != "" {
		b.WriteString(" | ")
		b.WriteString(source.URL)
	}
	b.WriteString("]\n")
	b.WriteString(source.Snippet)
	return b.String()
}

func hasUsableItinerary(itinerary domain.Itinerary) bool {
	return itinerary.TripID != "" && len(itinerary.Days) > 0
}

func trimBody(body []byte) string {
	text := strings.TrimSpace(string(body))
	if len(text) > 800 {
		return text[:800] + "..."
	}
	if text == "" {
		return "empty response body"
	}
	return text
}
